export const clientsData = [
    {
        id: 1,
        title: "Gadget Bodda",
        category: "Website",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757832351.jpg",
        image: "https://www.outletexpense.xyz/uploads/230-Motiur-Rahman/1757409080.png",
        description:
            "A full-stack e-commerce solution with payment integration, user authentication, and admin dashboard.",
        detailedDescription: "Gadget Bodda is a comprehensive e-commerce platform designed for electronics and gadgets retail. The platform features a modern, user-friendly interface with advanced product filtering, secure payment integration, and a powerful admin dashboard for inventory management.",
        challenge: "The client needed a scalable e-commerce solution that could handle high traffic during sales events while maintaining fast load times and secure transactions.",
        solution: "We built a full-stack solution using Next.js for optimal performance, integrated multiple payment gateways, and implemented a robust admin system for seamless operations.",
        client: "Gadget Bodda Ltd.",
        date: "2024",
        liveLink: "https://www.gadgetboddaa.com/",
        technologies: ["Next.js", "React", "Laravel", "Php"],
    },
    {
        id: 2,
        title: "Mobile Club",
        category: "Website",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757832398.jpg",
        image: "https://www.outletexpense.xyz/uploads/230-Motiur-Rahman/1757409274.png",
        description:
            "Mobile Club is a famous shop in Jamuna Future park in Bangladesh. They are sale used iPhone and Gadgets Accessories.",
        detailedDescription: "Mobile Club's digital storefront brings their premium used iPhone and gadget accessories business online. The platform features smooth animations, real-time inventory updates, and an engaging user experience that reflects their physical store's quality.",
        challenge: "Creating an online presence that matches the premium in-store experience while handling real-time inventory for used devices.",
        solution: "Developed a dynamic website with GSAP animations, Firebase for real-time data, and Next.js for performance, creating a seamless shopping experience.",
        client: "Mobile Club",
        date: "2024",
        liveLink: "https://www.mobileclub.co/",
        technologies: ["Next.js", "Firebase", "Gsap"],
    },
    {
        id: 3,
        title: "Satsuna Corporation",
        category: "Website",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834457.png",
        image: "https://www.outletexpense.xyz/uploads/230-Motiur-Rahman/1757409303.jpg",
        description:
            "Satsuna is a Japanese blog website. They publish famous blogs on Japan.",
        detailedDescription: "Satsuna Corporation's blog platform serves as a cultural bridge, publishing engaging content about Japanese culture, business, and lifestyle. The platform features a clean, modern design with excellent readability and API-driven content management.",
        challenge: "Building a multilingual blog platform that could handle rich media content while maintaining fast load times and SEO optimization.",
        solution: "Implemented a headless CMS approach with Next.js, integrated API for dynamic content, and optimized for both English and Japanese audiences.",
        client: "Satsuna Corporation",
        date: "2024",
        liveLink: "https://www.satsuna.co.jp",
        technologies: ["Next.js", "API Integration", "React"],
    },
    {
        id: 4,
        title: "CeL TeL",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834023.png",
        image: "https://www.outletexpense.xyz/uploads/230-Motiur-Rahman/1757409240.png",
        description:
            "A full-stack e-commerce solution with payment integration, user authentication, and admin dashboard.",
        liveLink: "https://www.celtelbd.com/",
        technologies: ["Next.js", "API Integration", "Tailwind"],
    },
    {
        id: 5,
        title: "Morshed Mart",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757833877.png",
        image: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757833724.png",
        description:
            "Morshed Mart is a fashion e-commerce store. They sell T-shirts and branded shirts.",
        liveLink: "https://www.morshedmart.com/",
        technologies: ["Next.js", "MySql"],
    },
    {
        id: 6,
        title: "Elite",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757833939.png",
        image: "https://www.outletexpense.xyz/uploads/230-Motiur-Rahman/1757409329.png",
        description:
            "Elite is a quality laptop seller. They sell many 2nd hand and new laptops.",
        liveLink: "https://www.eliteebd.com/",
        technologies: ["HTML", "CSS", "JavaScript"],
    },
    {
        id: 7,
        title: "Apple Newton Bd",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834132.jpg",
        image: "https://www.outletexpense.xyz/uploads/230-Motiur-Rahman/1757409124.png",
        description:
            "A full-stack e-commerce solution with payment integration, user authentication, and admin dashboard.",
        liveLink: "https://applenewtonbd.com/",
        technologies: ["React", "Express", "MySQL"],
    },
    {
        id: 8,
        title: "Shahensha Gadget",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834292.png",
        image: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834221.png",
        description:
            "A full-stack e-commerce solution with payment integration, user authentication, and admin dashboard.",
        liveLink: "https://shahenshahgadgets.com",
        technologies: ["React", "Express", "MySQL"],
    },
    {
        id: 9,
        title: "Apple Mart BD",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834693.png",
        image: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834622.png",
        description:
            "A full-stack e-commerce solution with payment integration, user authentication, and admin dashboard.",
        liveLink: "https://www.applemartbd.com",
        technologies: ["React", "Express", "MySQL"],
    },
    {
        id: 10,
        title: "EmusFashion",
        logo: "https://www.outletexpense.xyz/uploads/238-MD.-Sarawer-Jahan-Evan/1758168402.png",
        image: "/EmusFashion.png",
        description:
            "Modern fashion e‑commerce with curated categories, fast product discovery, and a streamlined checkout designed to increase conversions.",
        liveLink: "https://emusfashion.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
    {
        id: 11,
        title: "Brothers Mobile & Accessories",
        logo: "https://www.brothersmobilebd.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fdownload__4_-removebg-preview-removebg-preview%20(1).4b6af063.png&w=256&q=75&dpl=dpl_cxXAviRRxxRvewfH55T3iWYJzGet",
        image: "/Brothers Mobile & Accessories.png",
        description:
            "Retail experience for smartphones and accessories with clear product taxonomy, warranty info, and mobile‑first performance.",
        liveLink: "https://www.brothersmobilebd.com/",
        technologies: ["Next.js", "Tailwind", "SWR"],
    },
    {
        id: 13,
        title: "Outlet Expense",
        logo: "https://outletexpense.com/favicon.ico",
        image: "/Outlet Expense.png",
        description:
            "SaaS platform for expense tracking and outlet operations with dashboards, role‑based access, and real‑time insights.",
        liveLink: "https://outletexpense.com/",
        technologies: ["Next.js", "API Integration", "Tailwind"],
    },
    {
        id: 14,
        title: "Apple Daddy",
        logo: "https://www.appledaddybd.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Ffavicon.a0e81e1a.png&w=384&q=75&dpl=dpl_imvdJGmx7Rx6G9viBLLycAbU1M3f",
        image: "/Apple Daddy.png",
        description:
            "Apple‑focused retailer site featuring product comparisons, EMI details, and conversion‑optimized PDP and cart flow.",
        liveLink: "https://www.appledaddybd.com/",
        technologies: ["Next.js", "Tailwind", "SWR"],
    },
    {
        id: 15,
        title: "Perfect Gadget BD",
        logo: "https://www.perfectgadgetbd.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FPerfectGadgetBD-logo%20(1)%201.953d5536.png&w=128&q=75&dpl=dpl_Gnozm5sN5kDuE9hYgX68JMzafQty",
        image: "/Perfect Gadget BD.png",
        description:
            "Electronics and gadget storefront with fast catalog browsing, detailed specs, and secure checkout.",
        liveLink: "https://perfectgadgetbd.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
    {
        id: 16,
        title: "Taiba Mart",
        logo: "https://taibamart.com/_next/image?url=https%3A%2F%2Fwww.outletexpense.xyz%2Fuploads%2F243-Akhter-Hossain%2F1759820422.png&w=256&q=75",
        image: "/Taiba Mart.png",
        description:
            "A multi-category retail platform offering a wide range of household essentials, personal care products, home appliances, and lifestyle goods with easy navigation, clear pricing, and convenient delivery options across Bangladesh.",
        liveLink: "https://taibamart.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
    {
        id: 17,
        title: "PixelBD",
        logo: "https://www.gpixelbd.com/_next/image?url=https%3A%2F%2Fwww.outletexpense.xyz%2Fuploads%2F259-Shydul-Amir-Jihad%2F1761213710.png&w=96&q=75&dpl=dpl_DPrkuwpkUuyT8fShzus8ps3JWz1D",
        image: "/PixelBD.png",
        description:
            "A focused mobile-tech storefront in Bangladesh offering the latest smartphones, accessories and wearable devices with full specs, competitive pricing and reliable after-sales support.",
        liveLink: "https://www.gpixelbd.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
    {
        id: 18,
        title: "MKS Outfit",
        logo: "https://www.outletexpense.xyz/uploads/215-Rifat-Hasan/1762859683.png",
        image: "/MKS Outfit.png",
        description:
            "A fashion-ecommerce destination offering curated women’s (and possibly men’s) apparel and accessories with stylish seasonal collections, easy browsing of looks, and secure online checkout for shoppers in Bangladesh",
        liveLink: "https://www.mksoutfit.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
    {
        id: 19,
        title: "EmusCreation",
        logo: "https://www.emuscreation.com/favicon.ico",
        image: "/EmusCreation.png",
        description:
            "A creative studio offering video editing, branding, brand identity, and visual storytelling.",
        liveLink: "https://www.emuscreation.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
    {
        id: 20,
        title: "Apple Dream BD",
        logo: "https://appledreambd.com/logo.png",
        image: "/Apple Dream BD.png",
        description:
            "A dedicated Apple-ecosystem retailer in Bangladesh offering the latest iPhones, iPads and accessories with full spec details, authentic products and reliable delivery plus support.",
        liveLink: "https://appledreambd.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
    {
        id: 21,
        title: "Apple Nation BD",
        logo: "https://www.applenationbd.com/logo.png",
        image: "/Apple Nation BD.png",
        description:
            "A premier destination for Apple products in Bangladesh, featuring a wide range of iPhones, MacBooks, and accessories with competitive pricing and excellent customer service.",
        liveLink: "https://applenationbd.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
];
