export const clientsData = [
    {
        id: 1,
        title: "Gadget Bodda",
        category: "Website",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757832351.jpg",
        image: "/gadgetBodda.webp",
        fullScreenImage: "/[www.gadgetboddaa.com].webp",
        description:
            "A full-stack e-commerce solution with payment integration, user authentication, and admin dashboard.",
        detailedDescription: "Gadget Bodda is a comprehensive e-commerce platform designed for electronics and gadgets retail. The platform features a modern, user-friendly interface with advanced product filtering, secure payment integration, and a powerful admin dashboard for inventory management.",
        challenge: "The client needed a scalable e-commerce solution that could handle high traffic during sales events while maintaining fast load times and secure transactions.",
        solution: "We built a full-stack solution using Next.js for optimal performance, integrated multiple payment gateways, and implemented a robust admin system for seamless operations.",
        client: "Gadget Bodda Ltd.",
        date: "2024",
        liveLink: "https://www.gadgetboddaa.com/",
        technologies: ["Next.js", "React", "Laravel", "Php"],
    },
    // {
    //     id: 2,
    //     title: "Mobile Club",
    //     category: "Website",
    //     logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757832398.jpg",
    //     image: "https://www.outletexpense.xyz/uploads/230-Motiur-Rahman/1757409274.png",
    //     description:
    //         "Mobile Club is a famous shop in Jamuna Future park in Bangladesh. They are sale used iPhone and Gadgets Accessories.",
    //     detailedDescription: "Mobile Club's digital storefront brings their premium used iPhone and gadget accessories business online. The platform features smooth animations, real-time inventory updates, and an engaging user experience that reflects their physical store's quality.",
    //     challenge: "Creating an online presence that matches the premium in-store experience while handling real-time inventory for used devices.",
    //     solution: "Developed a dynamic website with GSAP animations, Firebase for real-time data, and Next.js for performance, creating a seamless shopping experience.",
    //     client: "Mobile Club",
    //     date: "2024",
    //     liveLink: "https://www.mobileclub.co/",
    //     technologies: ["Next.js", "Firebase", "Gsap"],
    // },
    // {
    //     id: 3,
    //     title: "Satsuna Corporation",
    //     category: "Website",
    //     logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834457.png",
    //     image: "https://www.outletexpense.xyz/uploads/230-Motiur-Rahman/1757409303.jpg",
    //     description:
    //         "Satsuna is a Japanese blog website. They publish famous blogs on Japan.",
    //     detailedDescription: "Satsuna Corporation's blog platform serves as a cultural bridge, publishing engaging content about Japanese culture, business, and lifestyle. The platform features a clean, modern design with excellent readability and API-driven content management.",
    //     challenge: "Building a multilingual blog platform that could handle rich media content while maintaining fast load times and SEO optimization.",
    //     solution: "Implemented a headless CMS approach with Next.js, integrated API for dynamic content, and optimized for both English and Japanese audiences.",
    //     client: "Satsuna Corporation",
    //     date: "2024",
    //     liveLink: "https://www.satsuna.co.jp",
    //     technologies: ["Next.js", "API Integration", "React"],
    // },
    {
        id: 4,
        title: "CeL TeL",
        category: "Website",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834023.png",
        image: "/celtelbd.webp",
        fullScreenImage: "/[www.celtelbd.com].webp",
        description:
            "A full-stack e-commerce solution with payment integration, user authentication, and admin dashboard.",
        liveLink: "https://www.celtelbd.com/",
        technologies: ["Next.js", "API Integration", "Tailwind"],
    },
    {
        id: 5,
        title: "Morshed Mart",
        category: "Website",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757833877.png",
        image: "morshedmart.webp",
        fullScreenImage: "/[www.morshedmart.com].webp",
        description:
            "Morshed Mart is a fashion e-commerce store. They sell T-shirts and branded shirts.",
        liveLink: "https://www.morshedmart.com/",
        technologies: ["Next.js", "MySql"],
    },
    {
        id: 6,
        title: "Elite",
        category: "Website",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757833939.png",
        image: "https://www.outletexpense.xyz/uploads/230-Motiur-Rahman/1757409329.png",
        description:
            "Elite is a quality laptop seller. They sell many 2nd hand and new laptops.",
        liveLink: "https://www.eliteebd.com/",
        technologies: ["HTML", "CSS", "JavaScript"],
    },
    {
        id: 7,
        title: "Apple Newton Bd",
        category: "Website",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834132.jpg",
        image: "https://www.outletexpense.xyz/uploads/230-Motiur-Rahman/1757409124.png",
        description:
            "A full-stack e-commerce solution with payment integration, user authentication, and admin dashboard.",
        liveLink: "https://applenewtonbd.com/",
        technologies: ["React", "Express", "MySQL"],
    },
    {
        id: 8,
        title: "Shahensha Gadget",
        category: "Website",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834292.png",
        image: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834221.png",
        description:
            "A full-stack e-commerce solution with payment integration, user authentication, and admin dashboard.",
        liveLink: "https://shahenshahgadgets.com",
        technologies: ["React", "Express", "MySQL"],
    },
    {
        id: 9,
        title: "Apple Mart BD",
        category: "Website",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834693.png",
        image: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834622.png",
        description:
            "A full-stack e-commerce solution with payment integration, user authentication, and admin dashboard.",
        liveLink: "https://www.applemartbd.com",
        technologies: ["React", "Express", "MySQL"],
    },
    {
        id: 10,
        title: "EmusFashion",
        category: "Website",
        logo: "https://www.outletexpense.xyz/uploads/238-MD.-Sarawer-Jahan-Evan/1758168402.png",
        image: "/EmusFashion.webp",
        fullScreenImage: "/[www.emusfashion.com].webp",
        description:
            "Modern fashion e‑commerce with curated categories, fast product discovery, and a streamlined checkout designed to increase conversions.",
        liveLink: "https://emusfashion.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
    {
        id: 11,
        title: "Brothers Mobile & Accessories",
        category: "Website",
        logo: "https://www.brothersmobilebd.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fdownload__4_-removebg-preview-removebg-preview%20(1).4b6af063.png&w=256&q=75&dpl=dpl_cxXAviRRxxRvewfH55T3iWYJzGet",
        image: "/Brothers Mobile & Accessories.webp",
        fullScreenImage: "/[www.brothersmobilebd.com].webp",
        description:
            "Retail experience for smartphones and accessories with clear product taxonomy, warranty info, and mobile‑first performance.",
        liveLink: "https://www.brothersmobilebd.com/",
        technologies: ["Next.js", "Tailwind", "SWR"],
    },
    {
        id: 13,
        title: "Outlet Expense",
        category: "Website",
        logo: "https://outletexpense.com/favicon.ico",
        image: "/Outlet Expense.webp",
        fullScreenImage: "/[www.outletexpense.com].webp",
        description:
            "SaaS platform for expense tracking and outlet operations with dashboards, role‑based access, and real‑time insights.",
        liveLink: "https://outletexpense.com/",
        technologies: ["Next.js", "API Integration", "Tailwind"],
    },
    {
        id: 14,
        title: "Apple Daddy",
        category: "Website",
        logo: "https://www.appledaddybd.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Ffavicon.a0e81e1a.png&w=384&q=75&dpl=dpl_imvdJGmx7Rx6G9viBLLycAbU1M3f",
        image: "/Apple Daddy.webp",
        fullScreenImage: "/[www.appledaddybd.com].webp",
        description:
            "Apple‑focused retailer site featuring product comparisons, EMI details, and conversion‑optimized PDP and cart flow.",
        liveLink: "https://www.appledaddybd.com/",
        technologies: ["Next.js", "Tailwind", "SWR"],
    },
    {
        id: 15,
        title: "Perfect Gadget BD",
        category: "Website",
        logo: "https://www.perfectgadgetbd.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FPerfectGadgetBD-logo%20(1)%201.953d5536.png&w=128&q=75&dpl=dpl_Gnozm5sN5kDuE9hYgX68JMzafQty",
        image: "/Perfect Gadget BD.webp",
        description:
            "Electronics and gadget storefront with fast catalog browsing, detailed specs, and secure checkout.",
        liveLink: "https://perfectgadgetbd.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
    {
        id: 16,
        title: "Taiba Mart",
        category: "Website",
        logo: "https://taibamart.com/_next/image?url=https%3A%2F%2Fwww.outletexpense.xyz%2Fuploads%2F243-Akhter-Hossain%2F1759820422.png&w=256&q=75",
        image: "/Taiba Mart.webp",
        fullScreenImage: "/[www.taibamart.com].webp",
        description:
            "A multi-category retail platform offering a wide range of household essentials, personal care products, home appliances, and lifestyle goods with easy navigation, clear pricing, and convenient delivery options across Bangladesh.",
        liveLink: "https://taibamart.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
    {
        id: 17,
        title: "PixelBD",
        category: "Website",
        logo: "https://www.gpixelbd.com/_next/image?url=https%3A%2F%2Fwww.outletexpense.xyz%2Fuploads%2F259-Shydul-Amir-Jihad%2F1761213710.png&w=96&q=75&dpl=dpl_DPrkuwpkUuyT8fShzus8ps3JWz1D",
        image: "/PixelBD.webp",
        fullScreenImage: "/[www.gpixelbd.com].webp",
        description:
            "A focused mobile-tech storefront in Bangladesh offering the latest smartphones, accessories and wearable devices with full specs, competitive pricing and reliable after-sales support.",
        liveLink: "https://www.gpixelbd.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
    {
        id: 18,
        title: "MKS Outfit",
        category: "Website",
        logo: "https://www.outletexpense.xyz/uploads/215-Rifat-Hasan/1762859683.png",
        image: "/MKS Outfit.webp",
        fullScreenImage: "/[www.mksoutfit.com].webp",
        description:
            "A fashion-ecommerce destination offering curated women’s (and possibly men’s) apparel and accessories with stylish seasonal collections, easy browsing of looks, and secure online checkout for shoppers in Bangladesh",
        liveLink: "https://www.mksoutfit.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
    {
        id: 19,
        title: "EmusCreation",
        category: "Website",
        logo: "https://www.emuscreation.com/favicon.ico",
        image: "/EmusCreation.webp",
        fullScreenImage: "/[emuscreation.vercel.app].webp",
        description:
            "A creative studio offering video editing, branding, brand identity, and visual storytelling.",
        liveLink: "https://www.emuscreation.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
    {
        id: 20,
        title: "Apple Dream BD",
        category: "Website",
        logo: "https://appledreambd.com/logo.png",
        image: "/Apple Dream BD.webp",
        fullScreenImage: "/[apple-dream-bd.vercel.app].webp",
        description:
            "A dedicated Apple-ecosystem retailer in Bangladesh offering the latest iPhones, iPads and accessories with full spec details, authentic products and reliable delivery plus support.",
        liveLink: "https://appledreambd.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
    {
        id: 21,
        title: "Apple Nation BD",
        category: "Website",
        logo: "https://www.applenationbd.com/logo.png",
        image: "/Apple Nation BD.webp",
        fullScreenImage: "/[apple-nation.vercel.app].webp",
        description:
            "A premier destination for Apple products in Bangladesh, featuring a wide range of iPhones, MacBooks, and accessories with competitive pricing and excellent customer service.",
        liveLink: "https://applenationbd.com/",
        technologies: ["Next.js", "Tailwind", "Framer Motion"],
    },
    {
        id: 22,
        title: "Day Planning",
        category: "Mobile Apps",
        logo: "https://play-lh.googleusercontent.com/rdgBuyy4IE4UWr6vEsjd0CFKTlnAmDtAzlVQg7FhbnkfL2X_6rIFQK9khsMVKw7TloMj=s96-rw",
        image: "/Day Planning.png",
        fullScreenImage: "/Day Planning.png",
        description:
            "Dayplaning : Your Ultimate Day Planner App for Seamless Daily Planning. Are you seeking a comprehensive solution for managing your daily life efficiently? Look no further - Dayplaning, the premier day planning app, is here to simplify your daily routine. With an array of high-quality features ranging from weather updates, currency management, smart notes, reminders, and news feeds to finance and task management, we&apos;ve got you covered, all within a secure environment.",
        liveLink: "https://play.google.com/store/apps/details?id=com.inayavintage.dailyplan",
        technologies: ["Flutter", "Firebase", "Tailwind", "Framer Motion"],
    },
    {
        id: 23,
        title: "Budget Buddy",
        category: "Mobile Apps",
        logo: "https://play-lh.googleusercontent.com/seMc7d09tQGOqMev79sToXW_IOHgi03V1MAfojcRKPmMRh82xzrUJYjlbXaN5ghIK9k=w480-h960-rw",
        image: "/Budget Buddy.png",
        fullScreenImage: "/Budget Buddy.png",
        description:
            "Budget Buddy is a comprehensive and user-centric budgeting application that empowers individuals to manage their finances effectively. In a world where financial management can be overwhelming, Budget Buddy is a reliable companion, offering a range of tools and features to simplify the budgeting process. Budget Buddy's standout feature is its customizable budget categories, allowing users to tailor their budgets to their unique lifestyles and financial objectives",
        liveLink: "https://play.google.com/store/apps/details?id=com.inayavintage.budgetpro",
        technologies: ["Flutter", "Firebase", "Tailwind", "Framer Motion"],
    },
    {
        id: 24,
        title: "Outlet Staff",
        category: "Mobile Apps",
        logo: "https://play-lh.googleusercontent.com/jeldgfwxzzZfLm_JzT0BkfJJyUE9B3i7I2ieN29MhsBKSM4jo0gNZwSTCS3RBTrwf9A=w480-h960-rw",
        image: "/Outlet Staff.png",
        fullScreenImage: "/Outlet Staff.png",
        description:
            "OutletStaff is the ultimate solution for businesses seeking to optimize their staff management processes. Our cutting-edge app empowers shop owners and marketing managers to effortlessly oversee their teams' activities in real-time. By harnessing the power of GPS technology and map APIs, staff can conveniently clock in and out, while administrators gain invaluable insights into their whereabouts with precise latitude and longitude tracking. This level of transparency enhances accountability, streamlines operations, and ensures optimal resource allocation.",
        liveLink: "https://play.google.com/store/apps/details?id=com.inayavintage.outletstaff",
        technologies: ["Flutter", "Firebase", "Tailwind", "Framer Motion"],
    },
    {
        id: 25,
        title: "Outlet Expense",
        category: "Mobile Apps",
        logo: "https://play-lh.googleusercontent.com/51zh_F_XXLXXQ0YMPbrN_DImGNmypFkDoVJOH_MbpGQVbGrLJAkBNbwxBGbMD-jiC_U=w480-h960-rw",
        image: "/Outlet Expense 2.png",
        fullScreenImage: "/Outlet Expense 2.png",
        description:
            "Introducing Outlet Expense, the indispensable tool for managing your finances with unparalleled ease! 🌟 Whether you're a business owner overseeing multiple outlets .Outlet Expense is here to simplify your financial management. Effortlessly monitor and control expenses across various outlets. With Outlet Expense, you can categorize expenditures, set budgets for each location, and gain valuable insights into your overall financial performance. From operational costs to inventory expenses, this tool empowers you to make informed decisions for the success of your business.",
        liveLink: "https://play.google.com/store/apps/details?id=com.inaya.outlet.expense",
        technologies: ["Flutter", "Firebase", "Tailwind", "Framer Motion"],
    },
    {
        id: 26,
        title: "Finance Goal",
        category: "Mobile Apps",
        logo: "https://play-lh.googleusercontent.com/Fgq2gWIvrpn0LFGP7OAcbvjKK2AQxNxEEPYYlWf_6Rta1Vh7LISaaZ0fE_h3OKWAYI8=w480-h960-rw",
        image: "/Finance Goal.png",
        fullScreenImage: "/Finance Goal.png",
        description:
            "Finance Goal is a cutting-edge financial planning application meticulously crafted to guide individuals on their path to financial prosperity. At its core, the app is a comprehensive toolkit for translating financial aspirations into tangible, achievable goals. Whether you're dreaming of a luxury vacation, purchasing your first home, or securing a comfortable retirement, Finance Goal is designed to be your unwavering companion throughout this transformative journey. Finance Goal's flexibility is a standout feature, allowing users to adapt their plans as circumstances change. The app accommodates a variety of financial goals, from emergency funds to debt reduction, offering tailored solutions for diverse financial scenarios. Users can set realistic timelines, allocate resources, and monitor progress with real-time updates, fostering a sense of control and confidence in their financial journey.",
        liveLink: "https://play.google.com/store/apps/details?id=com.inayavintage.goaltracker",
        technologies: ["Flutter", "Firebase", "Tailwind", "Framer Motion"],
    },
    {
        id: 27,
        title: "Spend Buddy - Finance Manager",
        category: "Mobile Apps",
        logo: "https://play-lh.googleusercontent.com/aauSkU3YeDfVZibnriDQYSXH9PN5Ep-AeHM4s1Fm4WS8U17dne5CYqH7xvrMrNjCYf6h=w480-h960-rw",
        image: "/Spend Buddy.png",
        fullScreenImage: "/Spend Buddy.png",
        description:
            "Spend Buddy is more than just a finance manager.it's your trusted partner in achieving financial wellness. Seamlessly blending user-friendly design with powerful features, Spend Buddy empowers users to take control of their finances easily.",
        liveLink: "https://play.google.com/store/apps/details?id=com.inayavintage.expensetracker",
        technologies: ["Flutter", "Firebase", "Tailwind", "Framer Motion"],
    },
    {
        id: 28,
        title: "Water Reminder",
        category: "Mobile Apps",
        logo: "https://play-lh.googleusercontent.com/Ydk-hyvxcfzUgDmv3fSheBJu-pdlZRWRZOapPtkRDrmLPPAduV9KpKJ3lEEaWg3f4H4=w480-h960-rw",
        image: "/Water Reminder.png",
        fullScreenImage: "/Water Reminder.png",
        description:
            "Introducing WaterReminder, your ultimate companion for optimal hydration and well-being! Our innovative app goes beyond simple reminders – it empowers you to calculate your personalized daily water intake based on factors like age, weight, and activity level. Stay on top of your health as WaterReminder sends timely alerts, ensuring you meet your hydration goals effortlessly. With easy-to-use features and a personalized touch, this app is your go-to solution for maintaining a healthy lifestyle. Make every sip count with WaterReminder and prioritize your well-being today!",
        liveLink: "https://play.google.com/store/apps/details?id=com.inayavintage.waterreminder",
        technologies: ["Flutter", "Firebase", "Tailwind", "Framer Motion"],
    },
    {
        id: 29,
        title: "Currency Converter Pro",
        category: "Mobile Apps",
        logo: "https://play-lh.googleusercontent.com/TvdOKKO5rKeT7DALahP8m4LTKRk0bDVJRJBzpHY1Ez2JFnqj0l4KnXrpdp0_CxBUmA=w480-h960-rw",
        image: "/Currency Converter Pro.png",
        fullScreenImage: "/Currency Converter Pro.png",
        description:
            "Real-time exchange rates. Key Features: Accurate Exchange Rates: Our app provides up-to-date, accurate exchange rates sourced from trusted financial institutions and data providers. You can trust our app for precise conversions. Easy-to-Use Calculator: We've designed a user-friendly calculator that lets you enter the amount you want to convert with ease. Input the values, choose your currencies, and get instant results. Real-Time Updates: Stay informed with real-time currency exchange rate updates.",
        liveLink: "https://play.google.com/store/apps/details?id=com.inayavintage.currency",
        technologies: ["Flutter", "Firebase", "Tailwind", "Framer Motion"],
    },
    {
        id: 30,
        title: "NewsWave - Live 24/7",
        category: "Mobile Apps",
        logo: "https://play-lh.googleusercontent.com/UJHOpCA-E2C4WYkyc0kQixiArTcU7SaaYc3LD5BHIV1ruqqZxa34HJwojzguwBZyXA=w480-h960-rw",
        image: "/NewsWave.png",
        fullScreenImage: "/NewsWave.png",
        description:
            "Introducing News Wave 24/7 - Your Ultimate News Portal! Looking for the perfect news app that keeps you updated with breaking news, live updates, sports highlights, entertaining stories, and the latest in politics, international affairs, and health? Your search ends here! News Wave 24/7 is your go-to news destination, providing you with an unmatched news-reading experience like never before. Our news app is designed to offer you the most comprehensive news coverage, with a focus on convenience and personalization. We believe in delivering news tailored to your preferences, which is why News Wave 24/7 goes beyond just providing news; it's a complete news portal that caters to your every need",
        liveLink: "https://play.google.com/store/apps/details?id=com.inayavintage.newshope",
        technologies: ["Flutter", "Firebase", "Tailwind", "Framer Motion"],
    },
];
