export const clients = [
    {
        id: 1,
        name: "Gadget Bodda",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757832351.jpg",
        website: "https://www.gadgetboddaa.com/",
    },
    {
        id: 2,
        name: "Mobile Club",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757832398.jpg",
        website: "https://www.mobileclub.co/",
    },
    {
        id: 3,
        name: "Satsuna Corporation",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834457.png",
        website: "https://www.satsuna.co.jp",
    },
    {
        id: 4,
        name: "CeL TeL",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834023.png",
        website: "https://www.celtelbd.com/",
    },
    {
        id: 5,
        name: "Morshed Mart",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757833877.png",
        website: "https://www.morshedmart.com/",
    },
    {
        id: 6,
        name: "Elite",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757833939.png",
        website: "https://www.eliteebd.com/",
    },
    {
        id: 7,
        name: "Apple Newton Bd",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834132.jpg",
        website: "https://applenewtonbd.com/",
    },
    {
        id: 8,
        name: "Shahensha Gadget",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834292.png",
        website: "https://shahenshahgadgets.com",
    },
    {
        id: 9,
        name: "Apple Mart BD",
        logo: "https://www.outletexpense.xyz/uploads/168-Khan-Sahadat/1757834693.png",
        website: "https://www.applemartbd.com",
    },
    {
        id: 10,
        name: "EmusFashion",
        logo: "https://www.outletexpense.xyz/uploads/238-MD.-Sarawer-Jahan-Evan/1758168402.png",
        website: "https://emusfashion.com/",
    },
    {
        id: 11,
        name: "Brothers Mobile & Accessories",
        logo: "https://www.brothersmobilebd.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fdownload__4_-removebg-preview-removebg-preview%20(1).4b6af063.png&w=256&q=75&dpl=dpl_cxXAviRRxxRvewfH55T3iWYJzGet",
        website: "https://www.brothersmobilebd.com/",
    },
    {
        id: 12,
        name: "Outlet Expense",
        logo: "https://www.outletexpense.com/_next/image?url=%2Foutletlogo.png&w=384&q=75",
        website: "https://www.outletexpense.com/",
    },
    {
        id: 14,
        name: "Apple Daddy",
        logo: "/apple-daddy.jpg",
        website: "https://www.appledaddybd.com/",
    },
    {
        id: 15,
        name: "Perfect Gadget BD",
        logo: "/perfectgadget.png",
        website: "https://perfectgadgetbd.com/",
    },
    {
        id: 16,
        name: "Taiba Mart",
        logo: "https://www.outletexpense.xyz/uploads/243-Akhter-Hossain/1759820422.png",
        website: "https://taibamart.com/",
    },
    {
        id: 17,
        name: "PixelBD",
        logo: "https://www.gpixelbd.com/_next/image?url=https%3A%2F%2Fwww.outletexpense.xyz%2Fuploads%2F259-Shydul-Amir-Jihad%2F1761213710.png&w=96&q=75&dpl=dpl_DPrkuwpkUuyT8fShzus8ps3JWz1D",
        website: "https://www.gpixelbd.com/",
    },
    {
        id: 18,
        name: "MKS Outfit",
        logo: "https://www.outletexpense.xyz/uploads/215-Rifat-Hasan/1762859683.png",
        website: "https://www.mksoutfit.com/",
    },
    {
        id: 19,
        name: "EmusCreation",
        logo: "/emuscreation.ico",
        website: "https://www.emuscreation.com/",
    },
    {
        id: 20,
        name: "Apple Dream BD",
        logo: "https://appledreambd.com/logo.png",
        website: "https://appledreambd.com/",
    },
    {
        id: 21,
        name: "Bhai Bhai Sewing Corner",
        logo: "https://www.outletexpense.xyz/uploads/129-Moinuddin-Khan/1731158069.jpg",
        website: "",
    },
    {
        id: 22,
        name: "Bonzer",
        logo: "https://www.outletexpense.xyz/uploads/131-Monjurul-Islam-Palash/1731585999.jpg",
        website: "",
    },
    {
        id: 23,
        name: "Accessories World",
        logo: "https://www.outletexpense.xyz/uploads/132-MD.-Haris-Naved/1731054817.jpg",
        website: "",
    },
    {
        id: 24,
        name: "Pochondoshop",
        logo: "https://www.outletexpense.xyz/uploads/137-Engr.-Ehsan-Ahmed/1734175886.jpg",
        website: "",
    },
    {
        id: 25,
        name: "Haque Pharma & Departmental Store",
        logo: "https://www.outletexpense.xyz/uploads/154-Haque-Pharma/1754285544.jpg",
        website: "",
    },
    {
        id: 26,
        name: "CELL TECH BD",
        logo: "https://www.outletexpense.xyz/uploads/159-MD-Rubel-Ahmed/1735368008.jpg",
        website: "",
    },
    {
        id: 27,
        name: "Niloy Electronics",
        logo: "https://www.outletexpense.xyz/uploads/164-MD-Halim/1737664516.jpg",
        website: "",
    },
    {
        id: 28,
        name: "Faizan International",
        logo: "https://www.outletexpense.xyz/uploads/184-Nazmul-Hasan-Rafi/1745673306.jpg",
        website: "",
    },
    {
        id: 29,
        name: "Exphone BD",
        logo: "https://www.outletexpense.xyz/uploads/186-Minhaz-Kazi/1741101597.jpg",
        website: "",
    },
    {
        id: 30,
        name: "CAFE LASANA",
        logo: "https://www.outletexpense.xyz/uploads/208-Aftabnogor-(Branch)/1747630312.jpg",
        website: "",
    },
    {
        id: 31,
        name: "Pixel Heaven",
        logo: "https://www.outletexpense.xyz/uploads/209-Rakib-Hassan-(Shouvo)/1747662715.jpg",
        website: "",
    },
    {
        id: 32,
        name: "Easy Phone Exchange",
        logo: "https://www.outletexpense.xyz/uploads/226-Minhazur-Rahman/1756375137.jpg",
        website: "",
    },
    {
        id: 33,
        name: "Khan Gadget BD",
        logo: "https://www.outletexpense.xyz/uploads/254-Sakib-Ali/1760274411.jpg",
        website: "",
    },
    {
        id: 34,
        name: "MAC TECHNOLOGY",
        logo: "https://www.outletexpense.xyz/uploads/255-MD.-Saiful-Islam-Rubel/1760275902.jpg",
        website: "",
    },
    {
        id: 35,
        name: "Badaner Dokan",
        logo: "https://www.outletexpense.xyz/uploads/257-Badan-Ray/1760619931.jpg",
        website: "",
    },
    {
        id: 36,
        name: "Apple Nation BD",
        logo: "https://www.outletexpense.xyz/uploads/260-Biplob-Hossen/1762065976.jpg",
        website: "",
    },
    {
        id: 37,
        name: "Dizmo",
        logo: "/dizmo.jpg",
        website: "",
    },
    {
        id: 38,
        name: "Zubo Society",
        logo: "/Zubo-Society.jpg",
        website: "",
    },
    {
        id: 39,
        name: "DLM Properties",
        logo: "/DLM-Properties.jpg",
        website: "",
    },
    {
        id: 40,
        name: "Afrin Pharma",
        logo: "/Afrin-Pharma.jpg",
        website: "",
    },
    {
        id: 41,
        name: "Honey Mart",
        logo: "/Honey_Mart.jpeg",
        website: "",
    },
    {
        id: 42,
        name: "Medee Gadgets",
        logo: "/Medee_Gadgets.jpeg",
        website: "",
    },
];
